// English equivalents for legacy UI copy that is still embedded in page components.
// The language provider applies these to text nodes and accessible attributes.
export const englishUi: Record<string, string> = {
  "Datos de entrada": "Input data",
  "Datos activos": "Active data",
  "Dataset de vuelos": "Flight dataset",
  "Tres matrices en un JSON": "Three matrices in one JSON",
  "Matriz de tiempos": "Travel time matrix",
  "Precios de clase turística": "Economy class fares",
  "Precios de primera clase": "First class fares",
  "CSV o Excel con flight_date, flight_time, origin, destination, aircraft_id, status y gate.": "CSV or Excel with flight_date, flight_time, origin, destination, aircraft_id, status, and gate.",
  "Opcional. Usa airports, travel_time, economy_fares y first_class_fares.": "Optional. Use airports, travel_time, economy_fares, and first_class_fares.",
  "JSON, CSV o Excel; valores en horas.": "JSON, CSV, or Excel; values in hours.",
  "JSON, CSV o Excel; vacío o null significa clase no disponible.": "JSON, CSV, or Excel; blank or null means this class is unavailable.",
  "Carga un dataset nuevo, una matriz, varias matrices o todos los archivos. El sistema combinará lo nuevo con los archivos activos y validará el resultado antes de reemplazar los datos.": "Upload a new dataset, one or more matrices, or all files. The system combines new files with active files and validates the result before replacing data.",
  "Dataset": "Dataset", "Filas de origen": "Source rows", "Aeropuertos en matrices": "Airports in matrices",
  "Cargando información actual…": "Loading current data…", "Seleccionar archivos": "Select files",
  "Para Excel de matrices, pon los aeropuertos de destino en la primera fila y los de origen en la primera columna. Las celdas contienen horas o precios. Solo necesitas seleccionar lo que deseas cambiar.": "For matrix spreadsheets, put destination airports in the first row and origin airports in the first column. Cells contain hours or fares. Select only the files you want to change.",
  "Explorar archivos": "Browse files", "Progreso": "Progress", "Filas:": "Rows:",
  "Vuelos admitidos:": "Eligible flights:", "Filas no importables:": "Rejected rows:",
  "Al procesar se borrarán todos los vuelos, boletos y reservas anteriores. Los archivos actuales no se modifican durante esta vista previa.": "Processing deletes all previous flights, tickets, and reservations. The current files are unchanged during this preview.",
  "Procesar y reemplazar datos": "Process and replace data", "Descargar rechazos por ruta (CSV)": "Download route rejections (CSV)",
  "Los aeropuertos de las matrices deben tener región, país y zona horaria en el catálogo actual. La vista previa cuenta como no importables las filas con fecha, avión o ruta no válidos.": "Matrix airports need a region, country, and time zone in the current catalog. The preview rejects rows with an invalid date, aircraft, route, or overlapping flight.",
  "Configuración Global": "Global settings", "Ajustes del sistema y personalización de marca para todos los nodos BD.": "System settings and branding for all database nodes.",
  "Preferencias del Sistema": "System preferences", "Nombre de la Aerolínea": "Airline name", "Modo de Sincronización DB": "Database synchronization mode",
  "En Tiempo Real (Recomendado)": "Real time (recommended)", "Asíncrono (Diferido 5m)": "Asynchronous (5 minute delay)", "Guardar Preferencias": "Save preferences",
  "Arrastra tu logo aquí": "Drop your logo here", "Formatos: PNG, JPG, SVG": "Formats: PNG, JPG, SVG", "Logo Asignado": "Assigned logo", "Personaliza tu Aerolínea": "Customize your airline",
  "Sube aquí el logotipo corporativo para visualizarlo en los recibos y el portal principal.": "Upload your company logo for receipts and the main portal.",
  "Panel de la aerolínea": "Airline dashboard", "Resumen de los vuelos cargados y las próximas salidas.": "Summary of imported flights and upcoming departures.",
  "Próximas salidas": "Upcoming departures", "Hasta 10 vuelos futuros. El catálogo completo incluye los vuelos históricos.": "Up to 10 future flights. The full catalog also includes historical flights.",
  "No hay salidas futuras. Los vuelos históricos están en el catálogo.": "There are no upcoming departures. Historical flights are in the catalog.",
  "Estado de servidores": "Server status", "Mapa de rutas próximas": "Upcoming route map", "Vista ilustrativa de los próximos vuelos consultados; no muestra los 29.000 registros a la vez.": "Illustration of upcoming flights; it does not show all 29,000 records at once.",
  "Abrir catálogo": "Open catalog", "Ver todos los vuelos": "View all flights", "Ver vuelos": "View flights", "Ver boletos": "View tickets", "Ver detalle": "View details", "Ver panel del vuelo": "View flight panel",
  "Estado de Vuelos": "Flight status", "Programado": "Scheduled", "En Vuelo": "In flight", "Salida": "Departure", "Aterrizado": "Landed", "Cargando mapa en vivo...": "Loading live map...",
  "Catálogo de vuelos": "Flight catalog", "Consulta los vuelos importados del CSV y los vuelos de demostración. Los registros históricos también aparecen aquí.": "Browse imported CSV flights and demonstration flights. Historical records are also listed here.",
  "Las horas de salida y llegada se muestran en la zona local de cada aeropuerto. Usa los filtros o «Ir a página» para explorar todo el catálogo.": "Departure and arrival times use each airport's local time zone. Use filters or Go to page to browse the full catalog.",
  "América registra primero en PostgreSQL América; Europa y Asia en PostgreSQL Europa/Asia. El país de arriba solo elige de dónde se consultan las listas. La salida usa la hora del aeropuerto de origen y la llegada la del destino.": "America is stored first in PostgreSQL America; Europe and Asia in PostgreSQL Europe/Asia. The country selector determines which node serves lists. Departure uses the origin airport's time, and arrival uses the destination's time.",
  "Todos los vuelos": "All flights", "Solo próximos": "Upcoming only", "Todos los orígenes": "All origins", "Todos los destinos": "All destinations", "Buscar vuelo por ID": "Find flight by ID", "Limpiar": "Clear",
  "Filas por página:": "Rows per page:", "Ir a página": "Go to page", "Ir": "Go", "Anterior": "Previous", "Siguiente": "Next",
  "No hay vuelos que coincidan con estos filtros. Prueba «Todos los vuelos» o limpia la búsqueda.": "No flights match these filters. Try All flights or clear the search.",
  "Registros válidos conservados, incluso históricos.": "Valid records retained, including historical flights.", "Importados del CSV": "Imported from CSV", "Vuelos de demostración": "Demonstration flights", "Programados para poder probar compras.": "Scheduled so you can test purchases.",
  "Nuevo Vuelo": "New flight", "Programar Vuelo": "Schedule flight", "Vuelo Directo": "Direct flight", "Avanzado (Escalas)": "Advanced (stopovers)", "Salida Inicial (Fecha y Hora)": "Initial departure (date and time)",
  "Salida Programada (Fecha y Hora)": "Scheduled departure (date and time)", "Seleccione Avión...": "Select aircraft...", "Seleccione Destino...": "Select destination...", "Seleccione Origen Inicial...": "Select initial origin...", "Seleccione Origen...": "Select origin...",
  "+ Seleccionar Destino Conectado...": "+ Select connected destination...", "Quitar Último": "Remove last", "Cancelar": "Cancel", "Cerrar": "Close",
  "Origen": "Origin", "Destino": "Destination", "Desde": "From", "Ruta": "Route", "Puerta": "Gate", "Avión": "Aircraft", "Aeronave": "Aircraft", "Estado": "Status", "Origen de datos": "Data source",
  "Salida local": "Local departure", "Llegada local": "Local arrival", "Horario local de cada aeropuerto": "Each airport's local time", "Salida Programada": "Scheduled departure", "Llegada Estimada": "Estimated arrival",
  "Vuelo": "Flight", "Vuelos": "Flights", "Boletos": "Tickets", "Boleto ID": "Ticket ID", "Asiento": "Seat", "Pasajero": "Passenger", "Nombre": "Name", "Disponible": "Available", "Reservado": "Reserved", "Vendido": "Sold",
  "Demostración": "Demo", "CSV importado": "Imported CSV", "Sin estado": "No status", "Primera Clase": "First class", "Clase Económica": "Economy class", "Regular": "Economy",
  "Venta de Boletos": "Ticket sales", "Busca tu destino, selecciona tu asiento y vuela con Pabon-go.": "Find your destination, choose a seat, and fly with Pabon-go.",
  "Buscar Vuelos": "Search flights", "Vuelos Disponibles": "Available flights", "No hay vuelos que coincidan con tu búsqueda.": "No flights match your search.",
  "También puedes buscar por origen y destino:": "You can also search by origin and destination:", "Sin Vuelo Seleccionado": "No flight selected",
  "Realiza una búsqueda y selecciona un vuelo de la lista de la izquierda para ver el mapa de asientos disponible.": "Search and select a flight from the list to see available seats.",
  "Información del Vuelo": "Flight information", "Mapa de Asientos": "Seat map", "Selección de Asiento": "Seat selection", "Asiento Deseado": "Selected seat", "Asiento Ocupado": "Occupied seat",
  "Haz clic en un asiento del mapa para ver los detalles del precio y completar tu reserva.": "Select a seat on the map to see its fare and complete your reservation.",
  "Este asiento ya ha sido reservado o vendido. Por favor selecciona otro.": "This seat has already been reserved or sold. Please choose another.",
  "Información del Pasajero": "Passenger information", "Datos de Contacto e Identificación": "Contact and identity details", "Capital desde donde compras (elige el servidor inicial)": "Purchase city (select the initial server)",
  "Precio Final": "Final price", "Precio Pagado": "Price paid", "Costo": "Cost", "Costo Total Estimado": "Estimated total cost", "Pre-Reservar (72h)": "Reserve (72h)", "Comprar Ticket Ahora": "Buy ticket now",
  "El boleto visual se descarga como PDF. Puedes volver a obtenerlo desde Gestión de Boletos.": "The visual ticket downloads as a PDF. You can download it again from Ticket Management.",
  "Ya compré un boleto · Ir a Gestión de Boletos": "I already bought a ticket · Go to Ticket Management", "Ver en Gestión de Boletos": "View in Ticket Management", "Ver boleto en Gestión": "View ticket in Management",
  "Consulta tus boletos, descarga el boleto visual o abre el pase en una billetera compatible.": "Browse your tickets, download the visual ticket, or open the pass in a compatible wallet.",
  "Gestión de Boletos": "Ticket Management", "Detalle del Boleto": "Ticket details", "Acciones de Estado": "Status actions", "Ningún Boleto Seleccionado": "No ticket selected", "No se encontraron boletos.": "No tickets found.",
  "Haz clic en un boleto de la lista de la izquierda para ver los detalles y actualizar su estado.": "Select a ticket from the list to see its details and update its status.",
  "Añadir a Apple Wallet": "Add to Apple Wallet", "Añadir a Google Wallet": "Add to Google Wallet",
  "El QR abre una página con la descarga y los pasos para importar el pase en Passbook. Usa la cámara del celular, no el lector de códigos de la app. Ambos dispositivos deben estar en la misma red.": "The QR code opens a page with the download and instructions for importing the pass into Passbook. Use the phone camera, not the app's code scanner. Both devices must be on the same network.",
  "El QR abre una página para descargar el pase y compartirlo desde Archivos a Passbook. Usa la cámara del celular, no el lector de códigos de la app. Ambos dispositivos deben estar en la misma red.": "The QR code opens a page to download the pass and share it from Files to Passbook. Use the phone camera, not the app's code scanner. Both devices must be on the same network.",
  "Escanea con la cámara del celular para abrir el pase": "Scan with your phone camera to open the pass", "Dirección actual del QR:": "Current QR address:",
  "Sugeridor de Rutas Inteligente": "Smart route suggestions", "Paso 1: Ciudad de Inicio": "Step 1: Starting city", "Menor Costo": "Lowest cost", "Menor Tiempo": "Shortest time", "Criterio de Optimización": "Optimization criterion",
  "Precios Sugeridos": "Suggested fares", "Ruta del Vuelo": "Flight route", "Tiempo de Viaje Estimado": "Estimated travel time", "Viaje Estimado": "Estimated trip", "Incluyendo escalas": "Including stopovers",
  "Sin Rutas Posibles": "No routes available", "No hemos podido encontrar una ruta que conecte estos destinos matemáticamente en estas condiciones.": "We could not find a route connecting these destinations under these conditions.",
  "Implementación de Algoritmo K-Shortest Paths (Dijkstra) para obtener el Top 3 de la ruta óptima minimizando costo o tiempo de vuelo.": "K shortest paths (Dijkstra) finds the top three routes by fare or flight time.",
  "Sincronización de servidores": "Server synchronization", "Refrescar": "Refresh", "Diferencias observables": "Observed differences", "Eventos detectados": "Detected events",
  "Indica si cada base de datos responde. No representa el avance de la sincronización.": "Shows whether each database responds. It does not show synchronization progress.",
  "Comparación de cantidades. Una diferencia de cero no verifica que cada versión sea idéntica.": "Count comparison. A difference of zero does not prove that every record version is identical.",
  "Horas locales. Se registran los cambios mientras la API está encendida.": "Local times. Changes are recorded while the API is running.",
  "Observación de conexiones reales. Detén o inicia un servidor y mira cómo cambia el sistema.": "Live connection status. Stop or start a server to see how the system responds.",
  "Operaciones esperando entrega completa:": "Operations awaiting full delivery:", "Cola pendiente:": "Pending queue:",
  "Si una PostgreSQL está caída, su cola local no puede consultarse y el total visible puede ser parcial.": "If a PostgreSQL node is down, its local queue cannot be read and the visible total may be incomplete.",
  "Esperando cambios de estado reales…": "Waiting for real status changes…", "Vuelos AM ↔ EU": "Flights AM ↔ EU", "Boletos AM ↔ EU": "Tickets AM ↔ EU", "Vuelos AM ↔ Mongo": "Flights AM ↔ Mongo", "Vuelos EU ↔ Mongo": "Flights EU ↔ Mongo",
  "Cargando panel del vuelo…": "Loading flight panel…", "Detalle del Vuelo": "Flight details", "← Volver a vuelos": "← Back to flights",
  "Verificación en vivo · Aerolíneas Pabón": "Live verification · Aerolíneas Pabón", "Número de boleto inválido.": "Invalid ticket number.",
  "Abrir pase para Passbook": "Open pass for Passbook", "Descargar pase para Passbook (ZIP)": "Download pass for Passbook (ZIP)",
  "Descarga el archivo y guárdalo en Passbook desde tu iPhone.": "Download the file and save it to Passbook from your iPhone.",
  "En el iPhone, toca el botón y guarda el ZIP en Archivos.": "On your iPhone, tap the button and save the ZIP in Files.",
  "Abre Archivos → Descargas y toca el ZIP para descomprimirlo.": "Open Files → Downloads and tap the ZIP to unzip it.",
  "Mantén pulsado el archivo": "Press and hold the file", "y genera el QR de nuevo.": "and regenerate the QR code.",
  "El ZIP contiene el mismo .pkpass de demostración. Apple Wallet oficial no acepta pases sin firma; usa la aplicación Passbook con la que ya comprobaste la importación.": "The ZIP contains the same demo .pkpass. Official Apple Wallet requires signed passes; use the Passbook app you used to verify the import.",
  "En iPhone, descarga el ZIP y comparte el .pkpass desde Archivos a Passbook. Apple Wallet oficial requiere firma de emisor.": "On iPhone, download the ZIP and share the .pkpass from Files to Passbook. Official Apple Wallet requires an issuer signature.",
  "No se encontraron resultados": "No results found", "País seleccionado:": "Selected country:", "Cargando Motor 3D...": "Loading 3D engine...",
  "Vista Previa 3D": "3D preview", "Vista 3D no disponible para este modelo. Puedes continuar con la compra.": "3D preview is unavailable for this model. You can continue with the purchase.",
  "Vista 3D no disponible. Puedes continuar con la compra.": "3D preview is unavailable. You can continue with the purchase.",
  "Buscar Top 3 Rutas": "Find top three routes", "Buscar vuelo": "Find flight", "Buscar país...": "Search countries...",
  "Buscar número de boleto, pasajero, email o pasaporte...": "Search ticket number, passenger, email, or passport...",
  "Cupos sin consultar": "Seats not checked", "CSV histórico y vuelos de demostración": "Historical CSV and demonstration flights", "CSV histórico y vuelos de demostración.": "Historical CSV and demonstration flights.",
  "Ingresos Primera": "First class revenue", "Ingresos Turística": "Economy revenue", "Reservados": "Reserved", "Disponibles": "Available",
  "Vuelos con asientos cargados": "Flights with seats loaded", "Vuelos próximos": "Upcoming flights", "Vuelos que coinciden": "Matching flights", "Vuelos registrados": "Registered flights",
  "Sin conexión": "Disconnected", "Sin lectura": "No reading", "Sin observación actual": "No current observation", "Funcionamiento con un nodo no disponible": "Operating with one unavailable node",
  "Panel no disponible": "Dashboard unavailable", "Pase no disponible": "Pass unavailable", "Boleto válido": "Valid ticket", "En vuelo": "In flight",
  "Solo salidas futuras; los históricos están en Todos.": "Only future departures; historical flights are under All.",
  "El PostgreSQL principal no responde; MongoDB ofrece una copia global de lectura. Las reservas requieren PostgreSQL.": "The primary PostgreSQL node is unavailable; MongoDB provides a global read copy. Reservations require PostgreSQL.",
  "La ruta cambia a MongoDB si el PostgreSQL principal deja de responder. Las reservas se guardan según el vuelo y su réplica.": "Reads switch to MongoDB if the primary PostgreSQL node stops responding. Reservations are stored with the flight and its replica.",
  "Ruta Óptima": "Optimal route", "Calcular ruta": "Calculate route", "Tipo de vuelos": "Flight type", "CARGANDO": "LOADING", "Descargando PDF...": "Downloading PDF...", "Descargar boleto visual (PDF)": "Download visual ticket (PDF)",
  "Verificando boleto…": "Verifying ticket…", "No se pudo verificar el boleto.": "Could not verify the ticket.", "El boleto no es válido o ya no está vigente.": "The ticket is invalid or no longer valid.",
  "Este código QR no contiene un boleto válido.": "This QR code does not contain a valid ticket.",
  "No se pudo cargar el panel del vuelo.": "Could not load the flight dashboard.", "No se pudo consultar el catálogo de vuelos.": "Could not load the flight catalog.",
  "No se pudo consultar el vuelo.": "Could not load the flight.", "No se pudo consultar el vuelo. Inténtalo de nuevo.": "Could not load the flight. Try again.",
  "No se pudieron cargar los asientos de este vuelo.": "Could not load seats for this flight.", "No se pudieron cargar los asientos de este vuelo. Inténtalo de nuevo.": "Could not load seats for this flight. Try again.",
  "No se pudo consultar el progreso": "Could not check progress", "No se pudieron validar los archivos": "Could not validate the files", "Error al validar": "Validation error", "Error al iniciar": "Start error",
  "Esto borrará todos los vuelos, boletos y reservas anteriores y los reemplazará usando los archivos seleccionados. ¿Continuar?": "This will delete all previous flights, tickets, and reservations and replace them using the selected files. Continue?",
  "⚠️ Este vuelo ya no admite reservas ni compras.": "⚠️ This flight no longer accepts reservations or purchases.",
  "⚠️ Por favor completa todos los datos del pasajero antes de continuar.": "⚠️ Complete all passenger details before continuing.",
  "⚠️ No se pudo completar la solicitud. Revisa la conexión e inténtalo de nuevo.": "⚠️ Could not complete the request. Check your connection and try again.",
  "El boleto quedó guardado, pero la confirmación de réplica está pendiente. Consulta su estado en Gestión de Boletos.": "The ticket was saved, but replica confirmation is pending. Check its status in Ticket Management.",
  "No se pudo descargar el boleto visual en PDF": "Could not download the visual ticket as a PDF", "Hubo un error actualizando el estado": "There was an error updating the status",
  "No se pudo iniciar el procesamiento": "Could not start processing", "Error de red. Asegúrate de que el servidor esté corriendo.": "Network error. Make sure the server is running.",
  "Ingresa un ID de vuelo válido.": "Enter a valid flight ID.",
  "Importados:": "Imported:", "vuelos de América y": "flights in America and", "de Europa/Asia. Ya puedes usar el sistema.": "in Europe/Asia. The system is ready.",
  "Última carga:": "Last upload:", "Mostrando": "Showing", "de": "of", "vuelos": "flights", "asientos disponibles": "seats available",
  "Actualización automática · última lectura": "Auto refresh · last checked", "Avión ID:": "Aircraft ID:",
  "El vuelo": "Flight", "existe, pero ya no admite compras.": "exists, but no longer accepts purchases.",
  "No se encontró el vuelo": "Flight not found:",
  "Manifiestos generados": "Generated manifests", "Asientos vendidos en todos los vuelos": "Seats sold across all flights",
  "Asientos reservados": "Reserved seats", "Estimación del modelo": "Model estimate", "No se pudo actualizar el panel. Los datos mostrados pueden estar desactualizados.": "Could not refresh the dashboard. The displayed data may be outdated.",
  "Cargando salidas…": "Loading departures…", "Consultando": "Checking", "Sale:": "Departs:", "Llega:": "Arrives:",
  "PostgreSQL América": "PostgreSQL America", "PostgreSQL Europa/Asia": "PostgreSQL Europe/Asia", "snapshot de MongoDB": "MongoDB snapshot", "ninguno": "none",
  "Abordando": "Boarding", "Despegó": "Departed", "Llegó": "Arrived", "Cancelado": "Cancelled", "Retrasado": "Delayed",
  "Administración": "Administration", "Aerolíneas Pabón · Pase de abordar": "Aerolíneas Pabón · Boarding pass", "Boleto:": "Ticket:", "Vuelo:": "Flight:",
  ". Abre esta dirección en el celular para comprobar que la red permite la conexión.": ". Open this address on your phone to check that the network connection works.",
  ". Fuente para consultar listas:": ". Source for list queries:",
  ". La sincronización con los demás nodos puede verse en el panel de Sincronización.": ". Synchronization with the other nodes is visible on the Synchronization page.",
  "No se detectó una dirección accesible desde el celular. Inicia el proyecto con": "No phone accessible address was detected. Start the project with",
  "América (Global)": "America (Global)", "Aterrizó": "Landed", "Filtrar ciudad/país...": "Filter city/country...",
  "La API no responde. El panel se actualizará cuando vuelva.": "The API is unavailable. The dashboard will refresh when it returns.",
  "Logo de Aerolínea": "Airline logo", "Navegación móvil": "Mobile navigation", "No existe un recorrido válido.": "There is no valid route.",
  "No se pudo cargar el catálogo de ciudades.": "Could not load the city catalog.", "No se pudo consultar el servidor.": "Could not reach the server.",
  "Número de Pasaporte": "Passport number", "Programar vuelo": "Schedule flight", "QR para abrir la guía de descarga del pase": "QR code to open pass download instructions",
  "Servidor": "Server", "Turística": "Economy", "boleto": "ticket", "el servidor disponible": "the available server",
  "Estados Unidos": "United States", "Estados Unidos de América": "United States of America", "Brasil": "Brazil", "Reino Unido": "United Kingdom", "España": "Spain", "Japón": "Japan", "Alemania": "Germany", "Emiratos Árabes Unidos": "United Arab Emirates", "Francia": "France", "Países Bajos": "Netherlands", "Canadá": "Canada", "Turquía": "Turkey", "Singapur": "Singapore",
  "Vuelo AP": "Flight AP", "Sale de": "Departs from", "Llega a": "Arrives in", "(hora local):": "(local time):", "Panel del vuelo AP": "Flight dashboard AP", "Capacidad": "Capacity", "Embarcando": "Boarding",
  "Error cargando ciudades:": "Error loading cities:", "Error de red procesando las escalas.": "Network error while processing stopovers.",
  "Validar y preparar": "Validate and prepare", "Buscar por ID de vuelo": "Search by flight ID", "Filtrar por origen": "Filter by origin", "Filtrar por destino": "Filter by destination", "Detalle": "Details",
  "Buscar por ID": "Search by ID", "Los tres servidores responden": "All three servers respond", "Consultando servidores…": "Checking servers…",
  "El país elige la fuente de la lista; no filtra los vuelos por origen.": "The country selects the list source; it does not filter flights by origin.",
  "Por favor selecciona al menos un origen y un destino final con escalas, además del avión y la fecha.": "Select an origin, a final destination with stopovers, an aircraft, and a date.",
  "Ruta óptima de la red dirigida. Los tramos representan rutas de la matriz, no reservas con horario.": "Optimal path on the directed route network. Legs are matrix routes, not scheduled bookings.",
  "⚠️ Error: La ruta seleccionada no tiene un tiempo de viaje definido.": "⚠️ Error: The selected route has no defined travel time.",
  "🚫 Esta ruta no está permitida. Por favor selecciona un destino habilitado.": "🚫 This route is unavailable. Select an enabled destination.",
  // Redesigned interface
  "Viajar": "Travel",
  "Rutas": "Routes",
  "Operación": "Operations",
  "Sistema distribuido": "Distributed system",
  "Sistema de reservas distribuido": "Distributed booking system",
  "Navegación principal": "Main navigation",
  "Idioma": "Language",
  "País de compra": "Purchase country",
  "Aerolíneas": "Airlines",
  "Anulado": "Cancelled",
  "Reembolso en curso": "Refund in progress",
  "Comprar un boleto": "Book a ticket",
  "Planificar una ruta": "Plan a route",
  "Ver sincronización": "View synchronization",
  "Aerolíneas Rafael Pabón": "Rafael Pabón Airlines",
  "Operaciones de vuelo": "Flight operations",
  "Tipo de vuelo": "Flight type",
  "Sin resultados": "No results",
  "ID del vuelo": "Flight ID",
  "Resultado de los filtros actuales.": "Result of the current filters.",
  "Desconocido": "Unknown",
  "Fabricante desconocido": "Unknown manufacturer",
  "No asignado": "Not assigned",
  "Reintentar": "Retry",
  "No se pudo cargar la lista.": "Could not load the list.",
  "Por favor completa todos los campos del formulario.": "Please complete every field in the form.",
  "Reservas": "Bookings",
  "Pasos de la compra": "Purchase steps",
  "Elegir asiento": "Choose seat",
  "Pasajero y pago": "Passenger and payment",
  "Confirmación": "Confirmation",
  "Tipo de búsqueda": "Search type",
  "Por ruta": "By route",
  "Por número de vuelo": "By flight number",
  "Filtrar origen": "Filter origin",
  "Filtrar destino": "Filter destination",
  "Intercambiar origen y destino": "Swap origin and destination",
  "ID que aparece en Vuelos": "ID shown in Flights",
  "Sin vuelos": "No flights",
  "Cabina": "Cockpit",
  "Tu selección": "Your selection",
  "Ver el avión en 3D": "View the aircraft in 3D",
  "Nombre Completo": "Full name",
  "Email": "Email",
  "Pase de abordar": "Boarding pass",
  "Boleto": "Ticket",
  "Error al procesar la reserva/compra": "Could not process the booking or purchase",
  "Mis viajes": "My trips",
  "Buscar boletos": "Search tickets",
  "Filtrar por estado": "Filter by status",
  "Todos": "All",
  "Vendidos": "Sold",
  "En reembolso": "Refunding",
  "Anulados": "Cancelled",
  "Sin boletos": "No tickets",
  "Vista del pase de abordar": "Boarding pass preview",
  "Planificador": "Planner",
  "Aeropuerto Origen": "Origin airport",
  "Aeropuerto Destino": "Destination airport",
  "Rutas encontradas": "Routes found",
  "Directo": "Direct",
  "Itinerario": "Itinerary",
  "Escala": "Stopover",
  "Procesando Grafo...": "Processing graph...",
  "Topología": "Topology",
  "El monitor no responde": "The monitor is not responding",
  "Cada operación se guarda con relojes de Lamport y vectoriales y se replica a los otros nodos.": "Each operation is stored with Lamport and vector clocks and replicated to the other nodes.",
  "Vista previa": "Preview",
  "Procesando datos": "Processing data",
  "Datos listos": "Data ready",
  "Proceso interrumpido": "Process interrupted",
  "Preparando reemplazo": "Preparing replacement",
  "Volver a vuelos": "Back to flights",
  "Ocupación de la cabina": "Cabin occupancy",
  "Comprar en este vuelo": "Book this flight",
  "Capacidad:": "Capacity:",
  "asientos": "seats",
  "No se pudo validar": "Could not validate",
  // Application servers
  "Servidores de aplicación": "Application servers",
  "Tres servidores en zonas horarias distintas. Cada uno tiene su propio reloj de Lamport y su componente en el reloj vectorial.": "Three servers in different time zones. Each one has its own Lamport clock and its own component in the vector clock.",
  "Esta página la atiende:": "This page is served by:",
  "Servidor América": "America server", "Servidor Europa": "Europe server", "Servidor Asia": "Asia server",
  "La Paz": "La Paz", "Berlín": "Berlin", "Pekín": "Beijing",
  "Principal: importación y mantenimiento": "Primary: import and housekeeping",
  "Reloj de Lamport": "Lamport clock", "Reloj vectorial": "Vector clock",
  "Sin respuesta. Sus peticiones las atienden los otros servidores.": "No response. The other servers handle its requests.",
  "En dorado, la componente propia de cada servidor. Dos vectores son concurrentes cuando ninguno es mayor o igual al otro en todas sus componentes.": "Gold marks each server's own component. Two vectors are concurrent when neither is greater than or equal to the other in every component.",
  "Bases de datos": "Databases", "por el": "by the",
  "3 servidores · 3 bases de datos": "3 servers · 3 databases",
};

const patterns: Array<[RegExp, (...parts: string[]) => string]> = [
  [/^Mostrando (\d+)–(\d+) de ([\d.,]+) vuelos$/, (_, from, to, total) => `Showing ${from}–${to} of ${total} flights`],
  [/^Última carga: (.+)$/, (_, detail) => `Last upload: ${detail}`],
  [/^Importados: (.+) vuelos de América y (.+) de Europa\/Asia\. Ya puedes usar el sistema\.$/, (_, am, eu) => `Imported: ${am} flights in America and ${eu} in Europe/Asia. The system is ready.`],
  [/^Avión ID: (\d+)$/, (_, id) => `Aircraft ID: ${id}`],
  [/^Estado (\d+)$/, (_, id) => `Status ${id}`],
  [/^Actualización automática · última lectura (.+)$/, (_, time) => `Auto refresh · last checked ${time}`],
  [/^Operaciones esperando entrega completa: (.+)$/, (_, count) => `Operations awaiting full delivery: ${count}`],
  [/^(.+) asientos disponibles$/, (_, count) => `${count} seats available`],
  [/^El boleto #(\d+) quedó registrado, pero no se descargó el PDF\. Puedes intentarlo de nuevo desde Gestión de Boletos\.$/, (_, id) => `Ticket #${id} was recorded, but the PDF did not download. Try again from Ticket Management.`],
  [/^La compra del boleto #(\d+) quedó registrada, pero el pase no se pudo mostrar\. Puedes consultarlo en Gestión de Boletos\.$/, (_, id) => `Ticket #${id} was purchased, but the pass could not be displayed. You can find it in Ticket Management.`],
  [/^¿Estás seguro que deseas cambiar el estado a (.+)\?$/, (_, status) => `Are you sure you want to change the status to ${status}?`],
  [/^El vuelo AP-(\d+) existe, pero ya no admite compras\.$/, (_, id) => `Flight AP-${id} exists, but no longer accepts purchases.`],
  [/^No se encontró el vuelo AP-(\d+)\.$/, (_, id) => `Flight AP-${id} was not found.`],
  [/^Ver detalle del vuelo (\d+)$/, (_, id) => `View details for flight ${id}`],
  [/^Última vez activo: (.+)$/, (_, time) => `Last active: ${time}`],
  [/^Error al crear el tramo (.+) -> (.+): (.+)$/, (_, from, to, reason) => `Error creating leg ${from} -> ${to}: ${reason}`],
  [/^Error del servidor: (.+)$/, (_, reason) => `Server error: ${reason}`],
  [/^Seleccione Ciudad \((\d+)\)\.\.\.$/, (_, count) => `Select city (${count})...`],
  [/^Todos los Boletos \((\d+)\)$/, (_, count) => `All tickets (${count})`],
  [/^Responde en (\d+) ms$/, (_, time) => `Responds in ${time} ms`],
  [/^Alterna (\d+)$/, (_, n) => `Alternative ${n}`],
  [/^(\d+) escala\(s\)$/, (_, n) => `${n} stopover(s)`],
];

export function translateUiText(value: string): string {
  const trimmed = value.trim();
  const translated = englishUi[trimmed] ?? patterns.map(([pattern, replace]) => {
    const match = trimmed.match(pattern);
    return match ? replace(...match) : null;
  }).find(Boolean);
  if (!translated) return value;
  return value.replace(trimmed, translated);
}
